### PR TITLE
Refactor Website to provide base for future development

### PR DESCRIPTION
**Pull request by ayoisaiah**
Basically I reorganised the project files and deleted unneeded code. The summary of my changes are in [this commit message](https://github.com/ayoisaiah/albertlauncher.github.io/commit/67356d7655a01ec03f6e6f3febc285bd6b3f4f35).

It was necessary to do this in one swoop, hence the change to many files.

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
Oh no! Have you seen the [source](https://github.com/albertlauncher/documentation/tree/master/src) repo?

**Comment by ayoisaiah** [comment]
Oh goodness me, that's a huge blooper! So you mean you develop the website in the documentation repo, build there and push _site to albert.github.io?

**Comment by ManuelSchneid3r** [comment]
Yes the organization repo is more like the root dir of a webserver. There should be no source files.
My tree looks like:
```
manuel@argon documentation [master] $ tree -L 2
.
├── albertlauncher.github.io
│   ├── 2017
│   ├── css
│   ├── docs
│   ├── feed.xml
│   ├── fonts
│   ├── help
│   ├── img
│   ├── index.html
│   ├── js
│   └── news
├── publish.sh
├── README.md
└── src
    ├── _config.yml
    ├── css
    ├── _data
    ├── _docs
    ├── _drafts
    ├── feed.xml
    ├── fonts
    ├── help.md
    ├── img
    ├── _includes
    ├── index.md
    ├── js
    ├── _layouts
    ├── news.html
    ├── _posts
    ├── _sass
    └── _site
```
I run `jekyll s` in src and work in Atom. When I finished the work I `./publish` it.

**Comment by ManuelSchneid3r** [comment]
I updated the documentation repo. You should be able to clone it with submodules (see readme) and be able to start working in there. Sorry for this.

**Comment by ayoisaiah** [comment]
Ok thanks for the clarification. That's fine, I've never seen it done this way before, hence the confusion. Should send another PR today.

**Pull request closed without merging**
